title: Malak Bachri
logo: assests/portfolio-profile-picture.png
description: ğŸ“| Honors student at Southern Arkansas University ğŸ’»| Majoring in Computer Science with a ğŸ›¡ï¸Cybersecurity certification ğŸ§®| Minoring in Mathematics
#show_downloads: true
theme: jekyll-theme-minimal
